baseURL = 'https://antonioandb.github.io/'
languageCode = 'pt-br'
title = 'Antonio Barros'
theme = "PaperMod"
ShowBreadCrumbs = true
ShowScrollToTop = true
ShowWordCount = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true
assets = { disableHLJS = true }

[params.label]
text = "Antonio Barros"
icon = "/logo_ab.png"       # O caminho começa com / porque aponta para a pasta static
iconHeight = 35          # Ajuste a altura em pixels para alinhar com o texto

[params.homeInfoParams]
Title = "Notas Técnicas"
Content = """
Compartilho tutoriais, estudos e experiências sobre Linux, desenvolvimento, infraestrutura e software livre.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/antonioandb"



[[params.socialIcons]]
name = "x"
url = "https://x.com/antoniobarrosan"

[menu]

[[menu.main]]
identifier = "linux"
name = "* Linux"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "dev"
name = "* Desenvolvimento"
url = "/categories/desenvolvimento/"
weight = 20

[[menu.main]]
identifier = "infra"
name = "* Infraestrutura"
url = "/categories/infraestrutura/"
weight = 30

[[menu.main]]
identifier = "sobre"
name = "* Sobre"
url = "/sobre/"
weight = 40