baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'Antonio Barros'
theme = "PaperMod"
ShowBreadCrumbs = true
ShowScrollToTop = true
ShowWordCount = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true
assets = { disableHLJS = true }

[params.label]
text = "Antonio Barros"
icon = "/logo_ab.png"       # O caminho começa com / porque aponta para a pasta static
iconHeight = 35          # Ajuste a altura em pixels para alinhar com o texto

[params.homeInfoParams]
Title = "Minhas Notas Técnicas 🧠"
Content = """
Um repositório público do meu aprendizado sobre Linux, desenvolvimento, infraestrutura e arquitetura.

Aqui documento minhas descobertas, tutoriais e experiências para ajudar outras pessoas que estão no mesmo caminho.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/antonioandb"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/seuservidor"

[[params.socialIcons]]
name = "x"
url = "https://x.com/seuusuario"

[menu]

[[menu.main]]
identifier = "linux"
name = "🐧 Linux"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "dev"
name = "💻 Desenvolvimento"
url = "/categories/desenvolvimento/"
weight = 20

[[menu.main]]
identifier = "infra"
name = "🛠 Infraestrutura"
url = "/categories/infraestrutura/"
weight = 30

[[menu.main]]
identifier = "about"
name = "📖 Sobre"
url = "/about/"
weight = 40